theme: jekyll-theme-cayman
title: OpenClaw Extensions (For Discord)
description: Extensions for OpenClaw Discord Bots. Made by Warecario.
baseurl: "/OpenClaw-Extensions/docs"
plugins:
  - jekyll-seo-tag

favicon: /assets/webicon.png
